apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.name }}-service
  labels:
    app: {{ .Values.backend.name }}
spec:
  selector:
    app: {{ .Values.backend.name }}
  ports:
  - port: {{ .Values.backend.port }}
    targetPort: {{ .Values.backend.port }}
  type: ClusterIP
---
{{- if .Values.webAlias.enabled }}
# Service "web" - Alias service cho frontend proxy
# Frontend image có config: "proxy": "http://web:80" (trong package.json)
# Service này map web:80 -> nodejs-backend:3000
apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: {{ .Values.backend.name }}
spec:
  selector:
    app: {{ .Values.backend.name }}
  ports:
  - port: {{ .Values.webAlias.port }}
    targetPort: {{ .Values.backend.port }}
  type: ClusterIP
{{- end }}
