apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.name }}-service
  labels:
    app: {{ .Values.mysql.name }}
spec:
  selector:
    app: {{ .Values.mysql.name }}
  ports:
  - port: {{ .Values.mysql.port }}
    targetPort: {{ .Values.mysql.port }}
  clusterIP: None
